{
	"version": 1655240419,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/player-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/play-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/stop-sheet0.png",
		"images/border-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/foldericon-sheet0.png",
		"images/wave-sheet0.png",
		"images/full-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/antidote-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/kick1wavetiger-sheet0.png",
		"images/clap1wavesmokebr-sheet0.png",
		"images/kick2wave-sheet0.png",
		"images/hh1wavelosing-sheet0.png",
		"images/issue-sheet0.png",
		"images/particles.png",
		"images/designsemnome-sheet0.png",
		"media/_rgd_bs_deep-h_bassdrum_os (1).m4a",
		"media/_rgd_bs_deep-h_bassdrum_os (1).ogg",
		"media/antidote medallion bass loops 126bpm 2 f [sc].m4a",
		"media/antidote medallion bass loops 126bpm 2 f [sc].ogg",
		"media/kick (a).m4a",
		"media/kick (a).ogg",
		"media/smoke br clap.m4a",
		"media/smoke br clap.ogg",
		"media/hh.m4a",
		"media/hh.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"channel.html",
		"Amazon-Web-App-API.min.js",
		"Amazon-Web-App-API-tester.min.js",
		"tizen-iap.js",
		"cws-buy.js",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js",
		"adapter.js",
		"cordova.oauth2.js"
	]
}